# Generated by Django 4.2.5 on 2023-10-22 12:31

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=36)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogRecettes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, max_length=100, populate_from='name', unique=True)),
                ('tag', models.TextField(blank=True, max_length=200)),
                ('picture', models.CharField(blank=True, max_length=200)),
                ('url_picture', models.URLField(blank=True)),
                ('url_recipe', models.URLField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='recettes.category')),
            ],
            options={
                'verbose_name': 'Recette',
                'ordering': ['name'],
            },
        ),
    ]
