# Generated by Django 4.2.5 on 2023-10-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0002_remove_blogrecettes_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecettes',
            name='ingredient',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogrecettes',
            name='recipe',
            field=models.TextField(null=True),
        ),
    ]
