# Generated by Django 4.2.5 on 2023-10-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0004_blogrecettes_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogrecettes',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
