# Generated by Django 4.2.5 on 2023-12-02 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0005_alter_blogrecettes_note'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogrecettes',
            name='tag',
        ),
    ]
