# Generated by Django 4.2.5 on 2023-12-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recettes', '0006_remove_blogrecettes_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogrecettes',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
